// For Categories
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const FETCH_FUND_DETAILS = 'FETCH_FUND_DETAILS';
export const FETCH_FUND_DETAILS_START = 'FETCH_FUND_DETAILS_START';
export const FETCH_FUND_DETAILS_SUCCESS = 'FETCH_FUND_DETAILS_SUCCESS';
export const FETCH_FUND_DETAILS_FAIL = 'FETCH_FUND_DETAILS_FAIL';
